matrix:
  allow_failures:
    - os: windows

  include:

    - os: osx
      name: 'Node.js lts/* - E2E / Browserstack'
      language: node_js
      node_js: lts/* # latest LTS Node.js release
      addons:
        chrome: stable
      before_install:
         - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
      script:
        - npm run build
        - npm run start &
        - |
          # Run when PR opened with 'dependabot' in branch name
          if [[ $TRAVIS_PULL_REQUEST_BRANCH =~ ^dependabot\/ ]] || [[ $TRAVIS_BRANCH =~ ^dependabot\/ ]]; then
            travis_wait 60 npm run browserstack | pv -q -L 3k && sleep 30
          else
            npm run e2e:headless:chrome
          fi
        # https://github.com/travis-ci/travis-ci/issues/6018
        - sleep 10

    - os: osx
      language: node_js
      node_js: '8.15.1'

    - os: linux
      dist: xenial
      language: python
      node_js: 'lts/*'
      python: '3.7'
      sudo: required
      before_install:
        - python --version
        - python3 --version
        - nvm install lts/*

    - os: linux
      dist: xenial
      language: python
      node_js: '8.15.1'
      python: '3.7'
      sudo: required
      before_install:
        - python --version
        - python3 --version
        - nvm install 8.15.1

    - os: windows
      language: node_js
      node_js: '8.15.1'
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python --version
        - python -m ensurepip
        - pip install virtualenv
        - python -m venv $HOME/venv
        - source $HOME/venv/Scripts/activate
      cache:
        directories:
          - $HOME/venv
          - c:/Python37
          - c:/Python37/Scripts

    - os: windows
      language: node_js
      node_js: lts/* # latest LTS Node.js release
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python --version
        - python -m ensurepip
        - pip install virtualenv
        - python -m venv $HOME/venv
        - source $HOME/venv/Scripts/activate
      cache:
        directories:
          - $HOME/venv
          - c:/Python37
          - c:/Python37/Scripts

cache:
  directories:
    - node_modules
    - .python
  npm: true
  pip: true

install: npm install

script: npm test