env:
  global:
    - MOZ_HEADLESS=1
cache:
  directories:
    - node_modules
    - .python
  npm: true
  pip: true

matrix:
  include:

    - os: osx
      language: node_js
      node_js: '8.15.1'
      env:
        - E2E=true
      addons:
        chrome: stable
        firefox: latest
      before_install:
         - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"

    - os: osx
      language: node_js
      node_js: lts/* # latest LTS Node.js release

    - os: linux
      dist: xenial
      language: python
      node_js: '8.15.1'
      python: '3.7'
      sudo: required
      before_install:
        - python --version
        - python3 --version
        - nvm install 8.15.1

    # - os: linux
    #   dist: xenial
    #   language: python
    #   node_js: 'lts/*'
    #   python: '3.7'
    #   sudo: required
    #   before_install:
    #     - python --version
    #     - python3 --version
    #     - nvm install lts/*

    # - os: windows
    #   language: node_js
    #   node_js: '8.15.1'
    #   addons:
    #     chrome: stable
    #     firefox: latest
    #   before_install:
    #     - choco install python3
    #     - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    #     - python --version
    #     - python -m ensurepip
    #     - pip install virtualenv
    #     - python -m venv $HOME/venv
    #     - source $HOME/venv/Scripts/activate
    #   cache:
    #     directories:
    #       - $HOME/venv
    #       - c:/Python37
    #       - c:/Python37/Scripts

    # - os: windows
    #   language: node_js
    #   node_js: lts/* # latest LTS Node.js release
    #   addons:
    #     chrome: stable
    #     firefox: latest
    #   before_install:
    #     - choco install python3
    #     - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
    #     - python --version
    #     - python -m ensurepip
    #     - pip install virtualenv
    #     - python -m venv $HOME/venv
    #     - source $HOME/venv/Scripts/activate
    #   cache:
    #     directories:
    #       - $HOME/venv
    #       - c:/Python37
    #       - c:/Python37/Scripts

install: npm install
stages:
  # Run unit tests on every build
  - script: npm test

  # Only run e2e on the specified OSX build
  - if: os = osx AND env(E2E)
    script:
      - npm run build
      - npm run start &
      - npm run e2e:headless:chrome
      - npm run e2e:headless:firefox

  # Run browserstack on dependabot branches
  - if: branch =~ /^dependabot\/.*$/ AND os = osx AND env(E2E)
    script: travis_wait 60 npm run browserstack


