matrix:
  include:
    - os: osx
      language: node_js
      node_js: lts/* # latest LTS Node.js release


env:
  global:
    BROWSERSTACK_USER=${BROWSERSTACK_USER}
    BROWSERSTACK_ACCESS_KEY=${BROWSERSTACK_ACCESS_KEY}

cache:
  directories:
    - node_modules
    - .python
  npm: true
  pip: true

install: npm install

before_script:
  - npm run build:prod
  - npm run start

script:
  - npm run browserstack
  - npm run test
