matrix:
  include:
    - os: osx
      language: node_js
      node_js: lts/* # latest LTS Node.js release

cache:
  directories:
    - node_modules
    - .python
  npm: true
  pip: true

install: npm install

before_script:
  - npm run build
  - npm run start

script:
  - npm run browserstack
  - npm run test
