matrix:

  include:

    - os: linux
      dist: xenial
      language: python
      node_js: 'lts/*'
      python: '3.7'
      sudo: required

      install: npm install
      before_install:
        - python --version
        - python3 --version
        - nvm install lts/*
      script:
        - IGNORE_ERRORS=true npm run build
        - npm run start &
      after_success: travis_wait 50 npm run browserstack && sleep 10

cache:
  directories:
    - node_modules
    - .python
  npm: true
  pip: true
