env:
  global:
    - MOZ_HEADLESS=1
cache:
  directories:
    - node_modules
    - .python
  npm: true
  pip: true
matrix:
  include:
    - os: osx
      name: 'OSX - Dependabot e2e Chrome'
      language: node_js
      node_js: '8.15.1'
      addons:
        chrome: stable
      before_install:
         - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
      install: npm install
      script:
      - |
        if [[ $TRAVIS_BRANCH =~ /^dependabot\/.*$/ ]]; then
          npm run build
          npm start &
          npm run e2e:headless:chrome
        fi
